[package]
name = "fishinge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventsub_websocket = { path = "../eventsub_websocket" }
reqwest = "0.11.13"
